AWSTemplateFormatVersion: 2010-09-09

Description: |
  Template to build phonebook app with load balancer and RDS MySQL instance 

Parameters:

  pVpcId:
    Description: VPC for deployment
    Type: AWS::EC2::VPC::Id
  
Resources:

  rDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Front-end access to RDS
      VpcId: !Ref pVpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0

  rDatabaseServer:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 7
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: ferhan-phonebook-rds
      DBName: clarusway_phonebook
      #DBSubnetGroupName: String
      Engine: mysql
      EngineVersion: "8.0.34"
      MasterUsername: admin
      MasterUserPassword: "{{resolve:ssm-secure:/ferhan/phonebook/password:1}}"
      MultiAZ: false
      Port: "3306"
      PubliclyAccessible: true
      VPCSecurityGroups: 
        - !Ref rDBSecurityGroup


#Outputs: